### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'firefox_options'

### ISSUE THREAD

**Issue by StathisKap** [ahmed103/Tiktok-no-watermark#5]
```
[WDM] - Downloading: 19.0kB [00:00, 14.9MB/s]
Traceback (most recent call last):
  File "/Users/stathis/Code/TikTok_Downloader/Tiktok-no-watermark/tiktok_no_water_mark.py", line 81, in <module>
    launch_download()
  File "/Users/stathis/Code/TikTok_Downloader/Tiktok-no-watermark/tiktok_no_water_mark.py", line 50, in launch_download
    api = SeleniumUtils(update_info, **kwargs)
  File "/Users/stathis/Code/TikTok_Downloader/Tiktok-no-watermark/selenuim_utils.py", line 34, in __init__
    self.browser = webdriver.Firefox(**kwargs)
  File "/Users/stathis/.miniforge/lib/python3.9/site-packages/seleniumwire/webdriver.py", line 179, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'firefox_options'
```

**Comment by voxqhuy** [comment]
The browser option parameter firefox_options was deprecated in [Selenium 3.8.0](https://github.com/SeleniumHQ/selenium/blob/4c0404e9580050c488f714885adea712a6f2da0d/py/CHANGES#L368) I changed to use options parameter but still couldn't get it to work due to proxy failures.

**Comment by glebmiller** [comment]
is there a way to fix this?
